name: CI

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 30]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download dependencies
        run: ./gradlew dependencies

      - name: Assemble APK
        run: ./gradlew assemble

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest
